### ISSUE TITLE
NameError: name '__swig_getmethods__' is not defined

### ISSUE THREAD

**Issue by dominikstrb** [BlackLight/leap-sdk-python3#3]
Hi @BlackLight 

thank you very much for making this easy to install Python 3 SDK for the Leap Motion available! When I am trying to run a script that only contains `import Leap`, I am getting the following error: 

```
File "test.py", line 6, in <module>
    import Leap
  File "/home/dominik/repos/leap/lib/python3.8/site-packages/Leap.py", line 783, in <module>
    class Image(Interface):
  File "/home/dominik/repos/leap/lib/python3.8/site-packages/Leap.py", line 834, in Image
    __swig_getmethods__["data"] = data
NameError: name '__swig_getmethods__' is not defined
(psychopy) ~/repos/leap >>> python test.py                                                        [1]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import Leap
  File "/home/dominik/repos/leap/lib/python3.8/site-packages/Leap.py", line 783, in <module>
    class Image(Interface):
  File "/home/dominik/repos/leap/lib/python3.8/site-packages/Leap.py", line 834, in Image
    __swig_getmethods__["data"] = data
NameError: name '__swig_getmethods__' is not defined
```

I am guessing that this could be due to the wrong version of `swig` installed on my system (Arch linux currently has `4.0.2.1`). Do you have any idea how I could fix this?

Thanks,
Dominik

**Comment by blacklight** [comment]
The SDK is build against `swig3`. Unfortunately, [`swig3` has recently been removed](https://www.archlinux.org/packages/community/x86_64/swig3/files/) from the Arch repo and now only versions >=4 are supported on Arch.

To make things work you can either:

- Install a previous `swig3` from the [Arch Linux archive](https://archive.archlinux.org/packages/s/swig3/) - and make sure that it doesn't conflict with the system `swig` and it's built against the same libc.

- If that doesn't work, build `swig3` [from sources](https://sourceforge.net/projects/swig/files/swig/).

Then [change `build.sh`](https://github.com/BlackLight/leap-sdk-python3/blob/master/build.sh#L6) so that `$SWIG` points to the `swig3` executable instead of `swig`.

**Comment by dominikstrb** [comment]
Thank you for the quick answer!
